In [134]:


#####hassen deach
from PIL import Image
import numpy  as np
from  tkinter import*
#img=Image.open('C:/Users/MOHAMED LEMIN/Pi.jpg')

## une fonction permet d affiche un tableaux ##

def afficher_tableau(tableaux):
    n = len(tableaux)
    m = len(tableaux[0])
    for i in range(n):
        for j in range(m):
            print('{:>3d}'.format(tableaux[i][j])," ", end="")
        print()
    return


#Q1 Une fonction qui permet renvoie les corrdonnee de (i',j') de l image du pixel (i,j)
def transformation(i,j,n):
     
            
    if i%2==0 and j%2==0:

        (l,c)=(i//2,j//2)

    if i%2==0 and j%2 ==1:

        (l,c)=(i//2,(n+j)//2)

    if i%2==1 and j%2==0:

        (l,c)=((n+i)//2,j//2)

    if i%2==1 and j%2==1:

        (l,c)=((n+i)//2,(n+j)//2) #l et c sont image de i et j
            
               
    return l,c 

  #on peut test la fonction de cette par (1,1,8) :

#print(tableaux(1,1,8))
#Q2 Programme une fonction qui renvoie le tableau calculé après transformation


def photomaton(tableaux):
    n=len(tableaux)
    nouveaux_tableaux=[[0 for i in range(n)] for j in range(n)]
    for i in range(n):
        for j in range(n):
            a,b=transformation(i,j,n) # a et b sont l image de i et j par fonction de la transformations
            nouveaux_tableaux[a][b]=tableaux[i][j]

    return nouveaux_tableaux

#on peut test par 
tableaux=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]]

#tableaux_transformation=photomaton(tableaux)
#afficher_tableau(tableaux)

print("")

#print(" voila l' image " )

print("")
#afficher_tableau(tableaux_transformation)
#Q3 programme une fonction de photomaton_iterer

def photomaton_iterer(tableaux,k):
    n=len(tableaux)      
    nouveauv_table1=[[tableaux[i][j] for j in range(n)] for i in range(n)]

    for i in range(k):
    
         nouveauv_table1=photomaton(tableaux)
         
    return nouveauv_table1
print("\n")
#print("_____voila  l'interation de la transformation de photomaton ____\n")
tableaux =[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]]
print("\n")
#afficher_tableau(tableaux)

#photo_itrere=photomaton_iterer(tableaux,4)

print("\n")
for k in range(1,10):
    tableau_itere = photomaton_iterer(tableaux,k)
# pour reoeter chaque fois la photo_iterer
#print("--- intere_k =",k,"---")
print("\n")
#afficher_tableau(tableau_itere)

#photo_itrere=photomaton_iterer(tableaux,2)

print("\n")
#afficher_tableau(photo_itrere)
print("")
###########Activité 2 (Conversion tableau/image)#############
#Tableau vers image
#Q1 transfere tableaux vers image
import numpy as np
from PIL import Image
def tableaux_vers_image(tableaux):
    image=Image.fromarray(tableaux)
    return image.show()
#test
#tab=np.array([[128,192,128,192,128],[224,0,228,0,224],[228,228,228,228,228],[224,64,64,64,224],[192,192,192,192,192]])

#tableaux_vers_image(tab)

#Q2 transfere image vers tableaux
def image_vers_tableaux(image_path):
 
    with Image.open(image_path) as image:         
        im_arr = np.fromstring(image.tobytes(), dtype=np.uint8)
        im_arr= im_arr.reshape((image.size[1], image.size[0], 3))  
    
    return print(im_arr)
#jpg_image_to_array("C:/Users/MOHAMED LEMIN/Pi.jpg")

In [127]:
from PIL import Image

def image_vers_tableaux(im):
    img=Image.open(im)
    
    return str(np.asarray(img)) 
          

#afficher_tableau(image_vers_tableaux("C:/Users/MOHAMED LEMIN/Pi.jpg"))

In [119]:
def jpg_image_to_array(image_path):
 
    with Image.open(image_path) as image:         
        im_arr = np.fromstring(image.tobytes(), dtype=np.uint8)
        im_arr= im_arr.reshape((image.size[1], image.size[0], 3))  
    
    return print(im_arr)
jpg_image_to_array("C:/Users/MOHAMED LEMIN/Pi.jpg")

[[[123 119 116]
  [129 127 128]
  [125 125 125]
  ...
  [127 126 124]
  [129 125 124]
  [132 128 129]]

 [[123 122 120]
  [125 123 124]
  [125 123 124]
  ...
  [126 125 123]
  [126 124 125]
  [132 128 129]]

 [[123 122 120]
  [123 121 122]
  [123 121 122]
  ...
  [128 127 125]
  [127 125 126]
  [130 126 127]]

 ...

 [[ 31  28  21]
  [ 33  30  23]
  [ 33  30  25]
  ...
  [ 37  36  31]
  [ 38  39  34]
  [ 38  38  36]]

 [[ 32  29  22]
  [ 33  30  23]
  [ 32  29  24]
  ...
  [ 43  40  35]
  [ 37  36  32]
  [ 38  37  33]]

 [[ 34  31  24]
  [ 34  31  24]
  [ 32  29  24]
  ...
  [ 39  35  32]
  [ 40  36  33]
  [ 41  36  32]]]


C:\Users\MOHAME~1\AppData\Local\Temp/ipykernel_11680/4155677975.py:4: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  im_arr = np.fromstring(image.tobytes(), dtype=np.uint8)


In [27]:
# importation des librairies
from PIL import Image
for a in range(1,50):

    img=Image.open('C:/Users/MOHAMED LEMIN/Pi.jpg') 

      

   # rÈcupÈration de la largeur et hauteur de l’image

    colonne,ligne = img.size

    # crÈation d’une image de mÍme type

    imgF = Image.new(img.mode,img.size)

 

    #boucle de traitement des pixel

    for j in range(ligne):

        for i in range(colonne):

            pixel = img.getpixel((i,j))

            # on calcule le complement ‡ MAX pour chaque composante – effet nÈgatif

            
            if i%2==0 and j%2==0:

                (x,y)=(i//2,j//2)

            if i%2==0 and j%2==1:

                (x,y)=(i//2,(ligne+j)//2)

            if i%2==1 and j%2==0:

                (x,y)=((colonne+i)//2,j//2)

            if i%2==1 and j%2==1:

                (x,y)=((colonne+i)//2,(ligne+j)//2)

            imgF.putpixel((x,y), pixel)

            # composition de la nouvelle image

         

    # la fonction de PIL qui fait la mÍme chose

    #imgF = ImageChops.invert(img)    

    # affichage de l’image

    imgF.show()

    c=a+1

    imgF.save(img=Image.open('C:/Users/MOHAMED LEMIN/Pi.jpg'))

# fermeture du fichier image

img.close()

TypeError: save() missing 1 required positional argument: 'fp'

In [5]:
#Q1



def transformation(i,j,n):
    if i%2 == 0 and j%2 == 0:
        ii = i//2
        jj = j//2
    if i%2 == 0 and j%2 == 1:
        ii = i//2
        jj = (n+j)//2
    if i%2 == 1 and j%2 == 0:
        ii = (n+i)//2
#121
        jj = j//2
    if i%2 == 1 and j%2 == 1:
        ii = (n+i)//2
        jj = (n+j)//2
    return ii,jj
transformation(1,1,8)

(4, 4)